# Django Imports
from django.db import models
from django.utils.translation import gettext_lazy as _


class RoleChoices(models.TextChoices):
    ADMIN = ("ADMIN", _("Admin"))
    USER = ("USER", _("User"))


class IdentityProviderChoices(models.TextChoices):

    DOCUMENSO = "DOCUMENSO", _("Documenso")
    GOOGLE = "GOOGLE", _("Google")
    OIDC = "OIDC", _("OIDC")


class TokenIdentifierChoices(models.TextChoices):

    CONFIRMATION_EMAIL = "confirmation-email", _("Confirmation Email")
    PASSKEY_CHALLENGE = "PASSKEY_CHALLENGE", _("PASSKEY_CHALLENGE")


class EmailVerificationTokenStatusChoices(models.TextChoices):
    NOT_FOUND = "NOT_FOUND", "Not Found"
    VERIFIED = "VERIFIED", "Verified"
    EXPIRED = "EXPIRED", "Expired"
    ALREADY_VERIFIED = "ALREADY_VERIFIED", "Already Verified"


class UserSecurityAuditLogTypeChoices(models.TextChoices):

    ACCOUNT_PROFILE_UPDATE = "ACCOUNT_PROFILE_UPDATE", "Account Profile Update"
    ACCOUNT_SSO_LINK = "ACCOUNT_SSO_LINK", "Account SSO Link"
    AUTH_2FA_DISABLE = "AUTH_2FA_DISABLE", "Auth 2FA Disable"
    AUTH_2FA_ENABLE = "AUTH_2FA_ENABLE", "Auth 2FA Enable"
    PASSKEY_CREATED = "PASSKEY_CREATED", "PassKey Created"
    PASSKEY_UPDATED = "PASSKEY_UPDATED", "PassKey Updated"
    PASSKEY_DELETED = "PASSKEY_DELETED", "PassKey Deleted"
    PASSWORD_RESET = "PASSWORD_RESET", "Password Reset"
    PASSWORD_UPDATE = "PASSWORD_UPDATE", "Password Update"
    SIGN_IN = "SIGN_IN", "Sign In"
    SIGN_OUT = "SIGN_OUT", "Sign Out"
    SIGN_IN_FAIL = "SIGN_IN_FAIL", "Sign In "
    SIGN_IN_2FA_FAIL = "SIGN_IN_2FA_FAIL", "2FA Sign In Failed "
    SIGN_IN_PASSKEY_FAIL = "SIGN_IN_PASSKE_FAIL", "PASSKEY Sign In Failed "


UserUniqueFieldChoices = ("id", "email", "url")


SIGN_IN_ERROR_CODES = {
    "INCORRECT_EMAIL_PASSWORD": "INCORRECT_EMAIL_PASSWORD",
    "USER_MISSING_PASSWORD": "USER_MISSING_PASSWORD",
    "CREDENTIALS_NOT_FOUND": "CREDENTIALS_NOT_FOUND",
    "INTERNAL_SEVER_ERROR": "INTERNAL_SEVER_ERROR",
    "TWO_FACTOR_ALREADY_ENABLED": "TWO_FACTOR_ALREADY_ENABLED",
    "TWO_FACTOR_SETUP_REQUIRED": "TWO_FACTOR_SETUP_REQUIRED",
    "TWO_FACTOR_MISSING_SECRET": "TWO_FACTOR_MISSING_SECRET",
    "TWO_FACTOR_MISSING_CREDENTIALS": "TWO_FACTOR_MISSING_CREDENTIALS",
    "INCORRECT_TWO_FACTOR_CODE": "INCORRECT_TWO_FACTOR_CODE",
    "INCORRECT_TWO_FACTOR_BACKUP_CODE": "INCORRECT_TWO_FACTOR_BACKUP_CODE",
    "INCORRECT_IDENTITY_PROVIDER": "INCORRECT_IDENTITY_PROVIDER",
    "INCORRECT_PASSWORD": "INCORRECT_PASSWORD",
    "MISSING_ENCRYPTION_KEY": "MISSING_ENCRYPTION_KEY",
    "MISSING_BACKUP_CODE": "MISSING_BACKUP_CODE",
    "UNVERIFIED_EMAIL": "UNVERIFIED_EMAIL",
    "ACCOUNT_DISABLED": "ACCOUNT_DISABLED",
}
