# Generated by Django 5.2 on 2025-09-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('avatar_image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', related_query_name='team', to='user.avatarimage')),
                ('owner_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', related_query_name='owned_team', to='authentication.user')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('MEMBER', 'Member')], max_length=7)),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', related_query_name='team_member', to='team.team')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', related_query_name='team_membership', to='authentication.user')),
            ],
            options={
                'verbose_name': 'team member',
                'verbose_name_plural': 'team members',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(blank=True, through='team.TeamMember', to='authentication.user'),
        ),
        migrations.CreateModel(
            name='TeamMemberInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('MEMBER', 'Member')], max_length=7)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], max_length=10)),
                ('token', models.CharField(blank=True, max_length=255, unique=True)),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member_invites', related_query_name='team_member_invite', to='team.team')),
            ],
            options={
                'verbose_name': 'team membership invitation',
                'verbose_name_plural': 'team membership invitations',
            },
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='unique_user_team'),
        ),
        migrations.AddConstraint(
            model_name='teammemberinvite',
            constraint=models.UniqueConstraint(fields=('team', 'email'), name='unique_team_email'),
        ),
    ]
