import { env } from "next-runtime-env";

export const NEXT_PUBLIC_WEBAPP_URL = () => env("NEXT_PUBLIC_WEBAPP_URL");

export const IS_APP_WEB = process.env.NEXT_PUBLIC_WEB_PROJECT === "web";
export const IS_APP_WEB_I18N_ENABLED = true;

export const NEXT_PUBLIC_SIGNUP_DISABLED = () =>
  env("NEXT_PUBLIC_SIGNUP_DISABLED");

export const IS_BILLING_ENABLED = () =>
  env("NEXT_PUBLIC_FEATURE_BILLING_ENABLED");

export const NEXT_PRIVATE_INNGEST_APP_ID = () =>
  env("NEXT_PRIVATE_INNGEST_APP_ID");

export const NEXT_PRIVATE_JOBS_PROVIDER = () =>
  env("NEXT_PRIVATE_JOBS_PROVIDER");
export const INNGEST_EVENT_KEY = () => env("INNGEST_EVENT_KEY");
export const NEXT_PRIVATE_INTERNAL_WEBAPP_URL = () =>
  env("NEXT_PRIVATE_INTERNAL_WEBAPP_URL") ?? NEXT_PUBLIC_WEBAPP_URL();
export const TRIGGER_SECRET_KEY = () => env("TRIGGER_SECRET_KEY");
export const TRIGGER_API_URL = () => env("TRIGGER_API_URL");

export const API_BASE_URL = () => env("API_BASE_URL");

export const NEXT_PRIVATE_SMTP_HOST = () => env("NEXT_PRIVATE_SMTP_HOST");
export const NEXT_PRIVATE_SMTP_APIKEY = () => env("NEXT_PRIVATE_SMTP_APIKEY");
export const NEXT_PRIVATE_MAILCHANNELS_API_KEY = () =>
  env("NEXT_PRIVATE_MAILCHANNELS_API_KEY");
export const NEXT_PRIVATE_MAILCHANNELS_END_POINT = () =>
  env("NEXT_PRIVATE_MAILCHANNELS_END_POINT");
export const NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN = () =>
  env("NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN");

export const NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR = () =>
  env("NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR");

export const NEXT_PRIVATE_MAILCHANNELS_PRIVATE_KEY = () =>
  env("NEXT_PRIVATE_MAILCHANNELS_PRIVATE_KEY");

export const NEXT_PRIVATE_RESEND_API_KEY = () =>
  env("NEXT_PRIVATE_RESEND_API_KEY");

export const NEXT_PRIVATE_SMTP_TRANSPORT = () =>
  env("NEXT_PRIVATE_SMTP_TRANSPORT");

export const NEXT_PRIVATE_SMTP_PORT = () => env("NEXT_PRIVATE_SMTP_PORT");
export const NEXT_PRIVATE_SMTP_SECURE = () => env("NEXT_PRIVATE_SMTP_SECURE");
export const NEXT_PRIVATE_SMTP_APIKEY_USER = () =>
  env("NEXT_PRIVATE_SMTP_APIKEY_USER");
export const NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS = () =>
  env("NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS");
export const NEXT_PRIVATE_SMTP_SERVICE = () => env("NEXT_PRIVATE_SMTP_SERVICE");
export const NEXT_PRIVATE_SMTP_USERNAME = () =>
  env("NEXT_PRIVATE_SMTP_USERNAME");
export const NEXT_PRIVATE_SMTP_PASSWORD = () =>
  env("NEXT_PRIVATE_SMTP_PASSWORD");
export const NEXT_PRIVATE_SMTP_FROM_NAME = () =>
  env("NEXT_PRIVATE_SMTP_FROM_NAME");
export const NEXT_PRIVATE_SMTP_FROM_ADDRESS = () =>
  env("NEXT_PRIVATE_SMTP_FROM_ADDRESS");
