# Generated by Django 5.2 on 2025-08-19 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('bytes', models.TextField(default='base64-encoded image or binary string', verbose_name='bytes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.user')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='profile')),
                ('avatar_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', related_query_name='user', to='user.avatarimage', verbose_name='avatar image')),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.user',),
        ),
    ]
